### ISSUE TITLE
i7 Bootloop

### ISSUE THREAD

**Issue by TheNameIsNigel** [balopez83/Surface-Pro-7-Hackintosh#5]
Sorry for the issue,

When creating an installer USB for the Surface Pro 7 (i7/16GB/1TB) model, it installs to the SSD perfectly fine, but after the reboot with the installation, it shows About 29 minutes remaining and goes down sometimes to about 26, but constantly boot loops, trying with both the i5 and i7 plist. 

Trying both Ventura and Sonoma netted the same result, with different USB drives.

Secure boot disabled & enabled tried. Re-installed Windows 11 and also downloaded the latest firmware update+drivers before attempting re-install.

Is there any compatibility issues with that particular model and this EFI? 

Thanks!

**Comment by TheNameIsNigel** [comment]
More debug info as well:

─ CPU
  └── Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
      ├── Cores: 4
      ├── Threads: 8
      ├── SSE: SSE4.2
      └── SSSE3: Supported

─ Motherboard
  ├── Model: Surface Pro 7
  └── Manufacturer: Microsoft Corporation

─ GPU
  └── Intel(R) Iris(R) Plus Graphics
      ├── Device ID: 0x8A52
      ├── Vendor: 0x8086
      ├── PCI Path: PciRoot(0x0)/Pci(0x2,0x0)
      └── ACPI Path: \_SB.PCI0.GFX0

─ Memory
  ├── H9HCNNNCPNALHR-NEE (Part-Number)
  │   ├── Type: Unknown
  │   ├── Slot
  │   │   ├── Bank: BANK 0
  │   │   └── Channel: ChannelA-DIMM0
  │   ├── Frequency (MHz): 3733 MHz
  │   ├── Manufacturer: SK Hynix
  │   └── Capacity: 8192MB
  └── H9HCNNNCPNALHR-NEE (Part-Number)
      ├── Type: Unknown
      ├── Slot
      │   ├── Bank: BANK 2
      │   └── Channel: ChannelB-DIMM0
      ├── Frequency (MHz): 3733 MHz
      ├── Manufacturer: SK Hynix
      └── Capacity: 8192MB

─ Network
  └── Ice Lake-LP PCH CNVi WiFi
      ├── Device ID: 0x34F0
      ├── Vendor: 0x8086
      ├── PCI Path: PciRoot(0x0)/Pci(0x14,0x3)
      └── ACPI Path: \_SB.PCI0.CNVW

─ Audio
  ├── Realtek ALC274
  │   ├── Device ID: 0x0274
  │   └── Vendor: 0x10EC
  └── Unknown Sound Device
      ├── Device ID: 0x280F
      └── Vendor: 0x8086

─ Input
  ├── USB Input Device (USB)
  │   ├── Product ID: 0x07B2
  │   └── Vendor ID: 0x045E
  └── HID-compliant mouse
      ├── Product ID: 0x07B2
      └── Vendor ID: 0x045E

─ Storage
  ├── SanDisk Cruzer Glide
  │   ├── Type: Unspecified
  │   ├── Connector: USB
  │   └── Location: External
  ├── Generic- SD/MMC
  │   ├── Type: Unspecified
  │   ├── Connector: USB
  │   └── Location: External
  └── SAMSUNG KLFGGAR4AA-K0T0
      ├── Type: NVMe
      ├── Connector: PCI Express
      └── Location: Internal

**Comment by TheNameIsNigel** [comment]
Discovered the issue, my SP7 has a Samsung PM991 NVMe drive which just doesn't work in macOS. Fun.

**Comment by balopez83** [comment]
@TheNameIsNigel So I have run into that issue before. While yes it is not supported often there is another way around it. 

I can't check it at the moment but make sure nvramfix.kext is in the EFI and activated in the config. Activate thirdpartydrives in the config as well. 

I don't remember what else needed to be done but I believe it can be made to work. 

While not ideal you can alternatively install macOS to a large capacity low profile, high speed Samsung USB. It will allow you to boot and run macOS albeit slower than on an SSD but it is still functional. You can get a decent 256gb low profile high speed Samsung USB's on amazon for under $20 nowadays.

**Comment by balopez83** [comment]
@TheNameIsNigel You could also try patching macOS to run on hfs+ though that does introduce a lot of other issues so not ideal.
